package org.omg.PortableServer;


/**
* org/omg/PortableServer/SERVANT_RETENTION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/

public interface SERVANT_RETENTION_POLICY_ID
{

  /**
	 * The value representing SERVANT_RETENTION_POLICY_ID.
	 */
  public static final int value = (int)(21L);
}
